FROM rootproject/root:6.22.02-ubuntu20.04 AS deps 

USER root

WORKDIR /opt

COPY packages /opt/packages

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && apt-get -y install --no-install-recommends -y $(cat /opt/packages) \
    && rm -rf /var/lib/apt/lists/* \
    && echo /opt/root/lib >> /etc/ld.so.conf \
    && ldconfig \
    && apt-get clean




FROM deps AS reqs

USER root

COPY requirements.in /opt/requirements.in

WORKDIR /opt

SHELL ["/bin/bash", "-c"]

RUN python3 -m venv agvenv \
    && source agvenv/bin/activate \
    && python3 -m pip install pip-tools \
    && pip-compile requirements.in \
    && cat requirements.txt \
    && deactivate 

CMD ["bash"]

